While building bootstrapfs on fc6, I'm getting this
^M  Installing: NodeManager                  ##################### [114/119]Stopping Node Manager: [FAILED]^M
can not change context: migrate kernel feature missing and 'compat' API disabled: Function not implemented
Starting Node Manager: Traceback (most recent call last):
  File "/usr/share/NodeManager/nm.py", line 13, in ?
    import logger
  File "/usr/share/NodeManager/logger.py", line 32
    if name:
             ^
IndentationError: unindent does not match any outer indentation level
[FAILED]^M